INSERT INTO `code_press` VALUES ('03', '科学 ', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('04', '高等教育', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('09', '北京大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('111', '机械工业', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('113', '中国铁道', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('115', '人民邮电', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('120', '水利电力', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('121', '电子工业', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('125', '家电维修杂志社', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('1567', '北京希望电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('1568', '高等教育电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('300', '中国人民大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('301', '北京大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('302', '清华大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('5610', '辽宁大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('5611', '大连理工大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('5632', '大连海事大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('801', '清华大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('80124', '中国水利水电', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('80125', '中国电力', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('81005', '东北财经大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('81042', '辽宁师范大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('81044', '东北财经大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('81054', '东北大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('81084', '东北财经大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('81103', '辽宁师范', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('8177', '北京航空', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('88394', '大连理工大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('88402', '中国科技大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('88702', '中国人民大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('8871', '中国水利水电', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('88844', '上海交通大学 ', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('88845', '复旦大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('8999', '大连理工大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('89998', '北京科海电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('89999', '北京希望电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('899993', '北京科海电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900031', '北京希望电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900038', '中国电力', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900043', '机械工业', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900044', '北京希望电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900049', '北京希望电子 ', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900052', '电子工业 ', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900056', '北京希望电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900066', '机械工业', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900071', '北京希望电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900085', '电脑报社', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900088', '北京希望电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900094', '机械工业', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900101', '北京希望电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900107', '北京科海电子', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900109', '中国电力', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900617', '清华大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900630', '清华大学 ', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900631', '清华大学  ', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900635', '清华大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900637', '清华大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900641', '清华大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900642', '北京大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('900643', '清华大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('90074', '电子工业', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('LLLLLLL', '辽宁师范大学', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `code_press` VALUES ('yxbb', '音像版别', 'leaf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
